# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
BRINGE_NET="192.168.150."

MACHINES = {
  :centos7 => {
        :box_name => "centos/7",
	:ip => BRINGE_NET + "150",
#        :ip_addr => '192.168.150.150'
	:ip_int => "1",
  },
}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

#          box.vm.network "private_network", ip: boxconfig[:ip_addr]
	  box.vm.network "public_network", ip: boxconfig[:ip], bridge: 'enp3s0'

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision :shell do |s|
             s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          end

      end
  end
end

